### ISSUE TITLE
Apple Watch BUGS

### ISSUE THREAD

**Issue by Sosodu13** [mawaqit/mawaqit-mobile-i18n#46]
> Bonjour cela fais un moment que l’application ne marche pas sur ma montre Apple Watch cela me met en gris sur le bas et quand je clique pour voir la prière il me dit qu’il n’a pas de prière en favoris je voulais savoir si cela va être réglée merci barakallah o fikoum

**Link:** [Conversation with Benkahla](https://app.intercom.com/a/apps/piphhhai/inbox/inbox/all/conversations/191381900174269)

**Customer:** [Benkahla](https://app.intercom.com/a/apps/piphhhai/users/63de495b0c6fc0ff09e62241/all-conversations)
**Customer ID:** 11317
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/piphhhai/inbox/inbox/all/conversations/191381900174269) when this issue is closed.

**Comment by AnasElbattra** [comment]
@Sosodu13 Please create this issue on the mobile repo 
https://github.com/mawaqit/mobile-app/issues

**Comment by Sosodu13** [comment]
@AnasElbattra i'm sorry brother, thank you for the link
